apiVersion: 1

datasources:
  - name: Sentinel Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: sentinel-prometheus
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
